language: node_js
node_js: lts/*
env: POST_ASSET_IMAGE_CDN=true

# 只监听 source 分支的改动
branches:
  only:
  - source

# 缓存依赖，节省持续集成时间
cache: npm

before_install:
# 解密 RSA 私钥并设置为本机 ssh 私钥
- openssl aes-256-cbc -K $encrypted_1fc90f464345_key -iv $encrypted_1fc90f464345_iv -in .travis/travis.key.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
# 修改本机 ssh 配置，防止秘钥认证过程影响自动部署
- mv -fv .travis/ssh-config ~/.ssh/config
- git config --global user.name "printempw"
- git config --global user.email "printempw@gmail.com"

install:
# 安装 Hexo 及其依赖
- npm install
- git clone https://github.com/printempw/hexo-theme-murasaki.git themes/murasaki

script:
# 生成静态页面
- hexo clean
- hexo generate

after_success:
# 部署到 GitHub Pages
- hexo deploy
