# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: PRIN BLOG
subtitle: 半吊子全栈开发者的日常
description: 这里是 prin 的个人博客，基本上啥都写：开发心得分享，日常吐槽吹水，偶尔也会写点正经文字。
author: prin
language: zh-Hans
timezone: Asia/Shanghai

# URL
url: https://printempw.github.io
root: /
permalink: :name/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tag
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year/:title.md
default_layout: post
titlecase: false
external_link:
  enable: true
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
  技术: tech
  日常: diary
  随笔: essay
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

archive_generator:
  per_page: 40
  yearly: true
  monthly: true
  daily: false

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: murasaki

sitemap:
  path: sitemap.xml

feed:
  type: atom
  path: atom.xml
  limit: 20

stylus:
  compress: true

theme_config:
  # https://twitter.com/imas_official/status/1287398983267049473
  primary_color: "#f34e6c"
  favicon: /images/favicon.png
  keywords: "prin, prinsss, printempw, blog, 博客, 独立博客"
  canonical: true
  expired_warning: true
  menu_pages:
    archives:
      name: 归档
      path: /archives/
    friends:
      name: 朋友们
      path: /friends/
    about:
      name: 关于我
      path: /about/
  menu_links:
    github:
      name: GitHub
      path: https://github.com/prinsss
    twitter:
      name: Twitter
      path: https://twitter.com/printempw
    rss:
      name: RSS Feed
      path: /atom.xml
  toc: true
  lazyload:
    enable: true
    loading_image: images/loading.jpg
  disqus:
    enable: true
    shortname: blessing-studio
    api: https://disqus.printempw.workers.dev/api/
    apikey: 5O1HIIFsAWX3lBOQveU8qWPPAd2aLyf1fklehBAfcQ7S9Jo8y4acIrmyO2uxMD35
    admin: printempw
    admin_label: 博主
  post_views_counter:
    enable: true
    api: https://work.prinzeugen.net/api/pageviews
  google_font: https://fonts.loli.net
  google_analytics: UA-65656002-1
  google_analytics_api: https://ga.printempw.workers.dev/
  google_site_verification: GRFMvqszPSgldR5B46PfCl67MehNVagYoA9AtJpd8BA

# hexo-hide-posts
hide_posts:
  # Change the filter name to fit your need
  filter: hidden
  # Generators which you want to expose all posts (include hidden ones) to.
  # Common generators: index, tag, category, archive, sitemap, feed, etc.
  public_generators: [feed]
  # Add "noindex" meta tag to prevent hidden posts from being indexed by search engines
  noindex: false

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:prinsss/prinsss.github.io.git
  branch: master
  name: prin
  email: printempw@gmail.com
