name: Hexo Deploy

on:
  push:
    branches:
      - source

env:
  POST_ASSET_IMAGE_CDN: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout theme repo
        uses: actions/checkout@v2
        with:
          repository: prinsss/hexo-theme-murasaki
          ref: master
          path: themes/murasaki

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 17

      - name: Cache pnpm modules
        uses: actions/cache@v2
        id: pnpm-cache
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Set up pnpm and install dependencies
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.21.0
          run_install: |
            args: [--prefer-offline, --frozen-lockfile]

      - name: Set up environment
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          DEPLOY_KEY_OLD: ${{ secrets.DEPLOY_KEY_OLD }}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh
          echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
          echo "$DEPLOY_KEY_OLD" > ~/.ssh/old_key
          chmod 600 ~/.ssh/id_rsa ~/.ssh/old_key
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          cp .github/workflows/ssh_config ~/.ssh/config

      - name: Deploy
        run: |
          npx hexo deploy --generate
